[phases.setup]
# Changed 'ffmpeg-full' to 'ffmpeg' and added 'libx264' and 'libfdk_aac' for robust encoding.
nixPkgs = ['nodejs', 'ffmpeg', 'libx264', 'libfdk_aac'] 

[phases.install]
cmds = ['npm install']

[start]
cmd = 'npm start'
